language: node_js
node_js:
  - "8"
dist: trusty   # needed for chrome headless
sudo: required # needed for chrome headless
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - redis-server
before_install:
  - rvm install 2.5.0
  - rvm use 2.5.0
before_script:
  - node --version
  - ruby --version
  - postgres --version
  - redis-server --version
  - npm run lint
  - psql -c "CREATE USER nolan CREATE_DB;"
script: npm run test-browser
env:
  global:
  - PGPORT=5433
  matrix:
  - BROWSER=chrome:headless
  - BROWSER=firefox:headless
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  directories:
  - $HOME/.npm