language: node_js
node_js:
  - "8"
dist: trusty   # needed for chrome headless
sudo: required # needed for chrome headless
addons:
  chrome: stable
services:
  - postgresql
  - redis-server
before_install:
  - rvm install 2.5.0
before_script:
  - npm run lint
script: npm run test-browser
env:
  matrix:
  - BROWSER=chrome:headless
  - BROWSER=firefox:headless
branches:
  only:
  - master
  - /^greenkeeper/.*$/
cache:
  directories:
  - $HOME/.npm